<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ahammed" name="Default test" tests="1" failures="1" timestamp="25 Aug 2018 19:54:58 GMT" time="69.862" errors="0">
  <testcase name="feature" time="68.769" classname="runner.TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="junit.framework.ComparisonFailure: expected:&amp;lt;...or phone number you’ve entered doesn’t match any account. Sign up for an...&amp;gt; but was:&amp;lt;...you’ve entered doesn’t match any...&amp;gt;">
      <![CDATA[cucumber.runtime.CucumberException: junit.framework.ComparisonFailure: expected:<...or phone number you’ve entered doesn’t match any account. Sign up for an...> but was:<...you’ve entered doesn’t match any...>
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: junit.framework.ComparisonFailure: expected:<...or phone number you’ve entered doesn’t match any account. Sign up for an...> but was:<...you’ve entered doesn’t match any...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at steps.TC003_LoginWithInValidUserNameAndValidPass.the_email_you_ve_entered_doesn_t_match_any_account_appear(TC003_LoginWithInValidUserNameAndValidPass.java:37)
	at ✽.Then The email you’ve entered doesn’t match any account -appear(faceBook-Login.feature:21)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
